### ISSUE TITLE
Question about 'use StructArrays'

### ISSUE THREAD

**Issue by tfiers** [MasonProtter/MutableNamedTuples.jl#10]
Hi Mason,

I was wondering about the following line from the ReadMe:

> You should probably use [StructArrays.jl](https://github.com/JuliaArrays/StructArrays.jl) though.

I wondered why?

I'm thinking about Revise.
You can easily redefine and rename the components in code that creates a `Vector{MutableNamedTuple}`;
but not so if you define some `MyStruct` and create a `StructVector{MyStruct}`.
(Unless you rename the type but that's annoying)

**Comment by MasonProtter** [comment]
> I wondered why?

StructArrays has better data locality so it's faster, and it also is just better made.

> You can easily redefine and rename the components in code that creates a `Vector{MutableNamedTuple}`;
> but not so if you define some `MyStruct` and create a `StructVector{MyStruct}`.

Seems like a weird comparison to me. Why not use  `StructVector{NamedTuple{...}}` if you're okay with using `Vector{MutableNamedTuple{...}}`?

**Comment by tfiers** [comment]
Okay, yes, I tried my workflow with `StructVector{NamedTuple{...}}`, and that indeed allows exactly what I want (live renaming of 'structs'). Thanks for the help
