### ISSUE TITLE
Register MutableNamedTuples.jl in general registry

### ISSUE THREAD

**Issue by VEZY** [MasonProtter/MutableNamedTuples.jl#2]
Hi,

thank you for developing this package ! 

I'm developing a package and I'm considering using MutableNamedTuples as a dependency following answers to my [SO question](https://stackoverflow.com/questions/64229714/define-struct-programmatically-in-julia/64230476#64230476). 

It would be awesome if your package could be available from the general registry instead of this repo (better for reproducibility).

Would you consider registering your package ? 

I know `StructArrays.jl` is registered and you advise using it, but your package is much lighter and the interface is cleaner for my purpose. What I want to do is simply create mutable named tuples, e.g.:

```julia
x = MutableNamedTuple(a=1, b=2)
x.a = 2
```
And I'm not sure I can do that with `StructArrays.jl`.

**Comment by MasonProtter** [comment]
Hi @VEZY, yes I can register the package if you find it helpful. It'll take a few days to appear in the general registry. In the meantime, feel free to just copy-paste the relevant code, it's pretty minimal.

**Comment by MasonProtter** [comment]
@JuliaRegistrator register

**Comment by VEZY** [comment]
Thank you!

**Comment by MasonProtter** [comment]
Here's the PR to watch: https://github.com/JuliaRegistries/General/pull/22634
